# Generated by Django 4.1.3 on 2022-11-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaintApp', '0002_complaintmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintmaster',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=256),
        ),
    ]
